### ISSUE TITLE
Self-built digilent-agent crashes on macOS

### ISSUE THREAD

**Issue by therealprof** [Digilent/digilent-agent#6]
Hi guys,

since I cannot find a later version than 0.3.6 which has known issues on the download site I tried building it myself on El Capitan and here's what I get following the instructions in this repo (using qmake and make from the command line) to build e4fd8fbd989ddf8e0daa3cee47e1e6d0b42aee64 against Qt 5.9 installed via homebrew:

```
* thread #1: tid = 0x1a9549c, 0x000000010013d587 QtWidgets`QWidget::insertAction(QAction*, QAction*) + 279, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x23)
  * frame #0: 0x000000010013d587 QtWidgets`QWidget::insertAction(QAction*, QAction*) + 279
    frame #1: 0x0000000100020667 digilent-agent`MainWindow::createTrayIcon(this=0x00007fff5fbfe300) + 391 at mainWindow.cpp:80
    frame #2: 0x000000010001e9ce digilent-agent`MainWindow::MainWindow(this=0x00007fff5fbfe300, agent=0x0000000101448130, parent=0x0000000000000000) + 510 at mainWindow.cpp:28
    frame #3: 0x0000000100020785 digilent-agent`MainWindow::MainWindow(this=0x00007fff5fbfe300, agent=0x0000000101448130, parent=0x0000000000000000) + 37 at mainWindow.cpp:16
    frame #4: 0x000000010001ca34 digilent-agent`main(argc=1, argv=0x00007fff5fbfe420) + 292 at main.cpp:60
    frame #5: 0x00007fff86c075ad libdyld.dylib`start + 1
```

**Comment by samkristoff** [comment]
Commit 0ffeb74bbe2dc9da9272c572be16021f8b884cca should fix this by only adding the 'Check for Updates' menu item on Windows since the maintenance tool is not available on Mac/Linux. 

Please let us know if this resolves the issue for you @therealprof 

Thanks!

**Comment by therealprof** [comment]
The crash is fixed. Still doesn't detect the OpenScope, though...

**Comment by samkristoff** [comment]
Hey @therealprof,
This sounds like it might be the same issue we're discussing [here](https://forum.digilentinc.com/topic/4345-cant-add-device-to-waveforms-live/#comment-17132).  Can you share details about system there.

Thanks!

-Kristoff

**Comment by therealprof** [comment]
I'd love to but somehow I can't register...

> You did not pass the security check. Please try again.

... even though the password security is "very strong".

Anyhow, the device shows up as /dev/tty.usbserial-DA4C2E3 in the system but is not recognized by digilent-agent. sudo does not help either...
